version: "3.1"

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - 2002:6379
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "2003:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
  minio:
    container_name: minio
    command: server /data --console-address ":9001"
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=titikkoma
      - MINIO_ROOT_PASSWORD=Titikkoma123!
      - MINIO_BROWSER=on
      - MINIO_SERVER_URL=http://127.0.0.1:9000
    volumes:
      - "minio_data:/data"

  rabbitmq:
    image: rabbitmq:4.1-management-alpine
    container_name: rabbitmq
    user: 0:0
    ports:
      - "5672:5672" # Port for AMQP protocol
      - "15672:15672" # Port for the management UI
    environment:
      - RABBITMQ_DEFAULT_USER=titikkoma
      - RABBITMQ_DEFAULT_PASS=Titikkoma123!
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"

volumes:
  pgdata:
  rabbitmq_data:
  minio_data:
